"use client";

import { useState } from "react";

type OrderRecord = { id: string; orderNumber: string; status: string; paymentStatus: string; customerName: string; customerEmail: string; customerPhone: string; addressLine1: string; addressLine2: string | null; city: string; state: string; postalCode: string; totalPaise: number; trackingProvider: string | null; trackingNumber: string | null; trackingUrl: string | null; operatorNote: string | null; createdAt: string; items: Array<{ id: string; productName: string; sku: string; size: string | null; colour: string | null; quantity: number; lineTotalPaise: number }> };

const actions: Record<string, string[]> = { paid: ["packing", "refund_pending"], packing: ["shipped", "refund_pending"], shipped: ["delivered", "refund_pending"], delivered: ["refund_pending"] };

export default function OrdersDashboard({ initialOrders }: { initialOrders: OrderRecord[] }) {
  const [orders, setOrders] = useState(initialOrders); const [filter, setFilter] = useState("all"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  const visible = filter === "all" ? orders : orders.filter((order) => order.status === filter);
  async function transition(order: OrderRecord, action: string) {
    const provider = action === "shipped" ? window.prompt("Courier/provider name", order.trackingProvider ?? "") ?? "" : undefined;
    const trackingNumber = action === "shipped" ? window.prompt("Tracking number", order.trackingNumber ?? "") ?? "" : undefined;
    const trackingUrl = action === "shipped" ? window.prompt("HTTPS tracking URL (optional)", order.trackingUrl ?? "") ?? "" : undefined;
    const note = window.prompt("Operator note (optional)", order.operatorNote ?? "") ?? "";
    if (!window.confirm(`Change ${order.orderNumber} from ${order.status} to ${action}?`)) return;
    setBusy(order.id); setMessage("");
    try { const response = await fetch(`/api/admin/orders/${order.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, provider, trackingNumber, trackingUrl, note }) }); const body = await response.json() as { error?: string; status?: string }; if (!response.ok) throw new Error(body.error || "Order update failed."); setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status: body.status ?? action, trackingProvider: provider ?? item.trackingProvider, trackingNumber: trackingNumber ?? item.trackingNumber, trackingUrl: trackingUrl ?? item.trackingUrl, operatorNote: note || item.operatorNote } : item)); setMessage(`${order.orderNumber} updated to ${body.status ?? action}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Order update failed."); } finally { setBusy(""); }
  }
  return <section className="orders-dashboard"><div className="order-toolbar"><label>Status <select value={filter} onChange={(event)=>setFilter(event.target.value)}><option value="all">All</option>{["pending_payment","payment_failed","paid","packing","shipped","delivered","refund_pending","refunded","expired","cancelled"].map((status)=><option key={status}>{status}</option>)}</select></label><b>{visible.length} orders</b></div>{message&&<p className="admin-notice" role="status">{message}</p>}<div className="order-cards">{visible.map((order)=><article className="order-card" key={order.id}><header><div><span>{order.orderNumber}</span><h2>{order.customerName}</h2><small>{new Date(order.createdAt).toLocaleString("en-IN")}</small></div><strong data-status={order.status}>{order.status.replaceAll("_"," ")}</strong></header><div className="order-contact"><p>{order.customerEmail}<br/>{order.customerPhone}</p><p>{order.addressLine1}{order.addressLine2&&<><br/>{order.addressLine2}</>}<br/>{order.city}, {order.state} {order.postalCode}</p></div><ul>{order.items.map((item)=><li key={item.id}><span>{item.productName}<small>{[item.size,item.colour,item.sku].filter(Boolean).join(" · ")}</small></span><b>× {item.quantity}</b><strong>₹{(item.lineTotalPaise/100).toLocaleString("en-IN")}</strong></li>)}</ul><div className="order-total"><span>Payment: {order.paymentStatus}</span><b>₹{(order.totalPaise/100).toLocaleString("en-IN")}</b></div>{order.trackingNumber&&<p>Tracking: {order.trackingProvider} — {order.trackingNumber} {order.trackingUrl&&<a href={order.trackingUrl} target="_blank" rel="noreferrer">Open</a>}</p>}<div className="order-actions">{(actions[order.status]??[]).map((action)=><button key={action} disabled={busy===order.id} onClick={()=>transition(order,action)}>{action.replaceAll("_"," ").toUpperCase()}</button>)}</div></article>)}</div></section>;
}
