"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useCart } from "../lib/cart";
import type { StorefrontCatalog, StorefrontProduct as Product } from "../lib/catalog/types";

function Icon({ name, size=20 }:{ name:"search"|"user"|"heart"|"bag"|"menu"|"close"|"arrow"; size?:number }) {
  const paths = {
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    user:<><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-4.7 3.5-7 8-7s7.2 2.3 8 7"/></>,
    heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>,
    bag:<><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,
    menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>, close:<><path d="m6 6 12 12M18 6 6 18"/></>, arrow:<><path d="M5 12h14M14 7l5 5-5 5"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function ProductCard({ product, saved, cartReady, onSave, onAdd }:{ product:Product; saved:boolean; cartReady:boolean; onSave:()=>void; onAdd:()=>void }) {
  const discount = Math.round((1-product.price/product.mrp)*100);
  return <article className="product-card">
    <div className="product-image-wrap"><img className="product-image" src={product.image} alt={product.name}/>{product.badge&&<span className="product-badge">{product.badge}</span>}<button className={`save-button ${saved?"saved":""}`} onClick={onSave} aria-label={saved?`Remove ${product.name} from wishlist`:`Save ${product.name} to wishlist`}><Icon name="heart" size={18}/></button><button className="quick-add" onClick={onAdd} disabled={!product.available||!cartReady}>{product.available?"ADD TO BAG":"OUT OF STOCK"}</button></div>
    <div className="product-info">{product.rating!==undefined&&product.reviews!==undefined&&<div className="rating"><strong>{product.rating}</strong><span>★</span><i></i><small>{product.reviews}</small></div>}<Link className="product-link" href={`/products/${product.slug}`}><h3>{product.name}</h3></Link><p>{product.subtitle}</p><div className="price-row"><strong>₹{product.price.toLocaleString("en-IN")}</strong><del>₹{product.mrp.toLocaleString("en-IN")}</del><span>({discount}% OFF)</span></div></div>
  </article>;
}

export default function Storefront({ products, categories, source, supportWhatsapp }: StorefrontCatalog & { supportWhatsapp: string }) {
  const cart=useCart();
  const [query,setQuery]=useState(""); const [activeCategory,setActiveCategory]=useState("All"); const [sort,setSort]=useState("recommended");
  const [wishlist,setWishlist]=useState<string[]>([]); const [wishOnly,setWishOnly]=useState(false); const [bagOpen,setBagOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false);
  const filtered=useMemo(()=>{ const q=query.trim().toLowerCase(); let rows=products.filter(p=>(!wishOnly||wishlist.includes(p.id))&&(activeCategory==="All"||p.category===activeCategory)&&(!q||`${p.name} ${p.category} ${p.subtitle}`.toLowerCase().includes(q))); if(sort==="low")rows=[...rows].sort((a,b)=>a.price-b.price); if(sort==="high")rows=[...rows].sort((a,b)=>b.price-a.price); if(sort==="rating")rows=[...rows].sort((a,b)=>(b.rating??0)-(a.rating??0)); return rows; },[products,query,activeCategory,sort,wishOnly,wishlist]);
  const addToBag=(product:Product)=>{const variant=product.variants?.find(item=>item.available)??product;cart.addItem({sku:variant.sku,productId:product.id,slug:product.slug,name:product.name,image:product.image,colour:variant.colour,size:variant.size,unitPrice:variant.price});setBagOpen(true)};
  const goShop=(category?:string)=>{setWishOnly(false);if(category)setActiveCategory(category);document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})};
  return <main data-catalog-source={source}>
    <div className="announcement">INDIA LAUNCH <span>•</span> SECURE GUEST CHECKOUT <span>•</span> PERSONAL SUPPORT</div>
    <header className="site-header"><button className="mobile-menu" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Icon name="menu"/></button><a className="brand" href="#top" aria-label="HOUSEOFPASHM home"><span className="brand-mark">H</span><span><b>HOUSEOF</b><em>PASHM</em></span></a><nav className="desktop-nav" aria-label="Main navigation">{categories.slice(0,5).map(c=><button key={c.name} onClick={()=>goShop(c.name)}>{c.name.toUpperCase()}</button>)}<button onClick={()=>document.getElementById("story")?.scrollIntoView({behavior:"smooth"})}>OUR CRAFT</button></nav><label className="search-box"><Icon name="search" size={19}/><input value={query} onChange={e=>{setQuery(e.target.value);setWishOnly(false)}} placeholder="Search for kurtis, stoles and more" aria-label="Search products"/></label><div className="header-actions"><button aria-label="Profile"><Icon name="user"/><span>Profile</span></button><button aria-label="Wishlist" onClick={()=>{setWishOnly(true);setActiveCategory("All");document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}}><Icon name="heart"/><span>Wishlist</span>{wishlist.length>0&&<b>{wishlist.length}</b>}</button><button aria-label="Shopping bag" onClick={()=>setBagOpen(true)}><Icon name="bag"/><span>Bag</span>{cart.itemCount>0&&<b>{cart.itemCount}</b>}</button></div></header>
    <section id="top" className="hero"><div className="hero-copy"><span className="eyebrow">THE KASHMIR EDIT • 2026</span><h1>Crafted in the valley.<br/><em>Styled for everywhere.</em></h1><p>Discover handpicked Aari embroidery, graceful silhouettes and everyday pieces that carry the soul of Kashmir.</p><div className="hero-buttons"><button onClick={()=>goShop()}>SHOP THE COLLECTION <Icon name="arrow" size={18}/></button><button className="ghost" onClick={()=>document.getElementById("story")?.scrollIntoView({behavior:"smooth"})}>OUR STORY</button></div><div className="hero-proof"><span><b>Guest</b> checkout</span><span><b>Verified</b> stock at payment</span></div></div><div className="hero-visual"><img src="https://houseofkari.in/cdn/shop/files/IMG_5287.heic?v=1739602272&width=2002" alt="Woman wearing a navy Kashmiri embroidered kurta"/><div className="hero-caption"><i></i><span>Hand-finished details<br/><b>Made to be noticed</b></span></div></div></section>
    <section className="category-section"><div className="section-heading"><span>SHOP BY CATEGORY</span><h2>Find your kind of elegance</h2></div><div className="category-row">{categories.map(c=><button key={c.name} className={activeCategory===c.name?"active":""} onClick={()=>goShop(c.name)}><span><img src={c.image} alt=""/></span><b>{c.name}</b><small>EXPLORE →</small></button>)}</div></section>
    <section className="benefit-strip"><div><span>✦</span><p><b>Curated craftsmanship</b><small>Details inspired by Kashmir</small></p></div><div><span>↺</span><p><b>Clear policies</b><small>Review terms before payment</small></p></div><div><span>⌁</span><p><b>India-focused launch</b><small>Delivery details checked securely</small></p></div><div><span>♡</span><p><b>Personal assistance</b><small>Style help on WhatsApp</small></p></div></section>
    <section id="shop" className="shop-section"><div className="shop-head"><div><span>CURATED FOR YOU</span><h2>{wishOnly?"Your wishlist":activeCategory==="All"?"Trending now":activeCategory}</h2><p>{filtered.length} styles</p></div><div className="filter-controls"><div className="chips"><button className={activeCategory==="All"&&!wishOnly?"active":""} onClick={()=>{setActiveCategory("All");setWishOnly(false)}}>All</button>{categories.map(c=><button key={c.name} className={activeCategory===c.name&&!wishOnly?"active":""} onClick={()=>{setActiveCategory(c.name);setWishOnly(false)}}>{c.name}</button>)}</div><label>Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="rating">Customer rating</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option></select></label></div></div>{filtered.length?<div className="product-grid">{filtered.map(product=><ProductCard key={product.id} product={product} saved={wishlist.includes(product.id)} cartReady={cart.ready} onSave={()=>setWishlist(current=>current.includes(product.id)?current.filter(id=>id!==product.id):[...current,product.id])} onAdd={()=>addToBag(product)}/>)}</div>:<div className="empty-state"><h3>{wishOnly?"Your wishlist is empty":"No styles found"}</h3><p>{wishOnly?"Save your favourite pieces and find them here.":"Try a different search or browse all categories."}</p><button onClick={()=>{setQuery("");setActiveCategory("All");setWishOnly(false)}}>VIEW ALL STYLES</button></div>}</section>
    <section id="story" className="story-section"><div className="story-image"><img src="https://cdn.exoticindia.com/images/products/original/textiles-01-2025/gak603-lemonade_a04.webp" alt="Colourful Aari embroidered Kashmiri bag"/><span>THREAD BY THREAD</span></div><div className="story-copy"><span>BEAUTY WITH A BEGINNING</span><h2>Not just worn.<br/><em>Carried forward.</em></h2><p>HOUSEOFPASHM brings the valley’s visual poetry into the modern wardrobe—through joyful colour, delicate needlework and silhouettes made for real life.</p><div className="story-stats"><div><strong>01</strong><span>Curated pieces<br/>with character</span></div><div><strong>02</strong><span>Heritage details,<br/>modern styling</span></div><div><strong>03</strong><span>Personal service,<br/>wherever you are</span></div></div><a href="https://github.com/Ankush231994/houseofpashm" target="_blank" rel="noreferrer">VIEW THE PROJECT <Icon name="arrow" size={18}/></a></div></section>
    <section className="newsletter"><span>FOLLOW THE JOURNEY</span><h2>New pieces. Craft details. Styling notes.</h2><p>See the current HOUSEOFPASHM collection and contact the operator through the official channels.</p><a href="https://www.instagram.com/kashmir_elegance_official/" target="_blank" rel="noreferrer">VIEW INSTAGRAM</a></section>
    <footer><div className="footer-brand"><a className="brand" href="#top"><span className="brand-mark">H</span><span><b>HOUSEOF</b><em>PASHM</em></span></a><p>Bringing beauty from Kashmir to your wardrobe.</p><a href="https://github.com/Ankush231994/houseofpashm" target="_blank" rel="noreferrer">github.com/Ankush231994/houseofpashm</a></div><div><b>SHOP</b><a href="#shop">Kurtis</a><a href="#shop">Suit Sets</a><a href="#shop">Co-ord Sets</a><a href="#shop">Stoles & Bags</a></div><div><b>HELP</b><Link href="/policies/privacy">Privacy</Link><Link href="/policies/shipping">Shipping</Link><Link href="/policies/returns">Returns & exchanges</Link><Link href="/track-order">Track order</Link></div><div><b>TERMS</b><Link href="/policies/terms">Terms of sale</Link><Link href="/policies/cancellation">Cancellation & refunds</Link><b className="mt">PAY SECURELY</b><p>UPI • Cards • Netbanking</p></div><div className="copyright">© 2026 HOUSEOFPASHM. All rights reserved.<span>Crafted with care for a modern Kashmir.</span></div></footer>
    {menuOpen&&<div className="mobile-drawer"><button className="drawer-close" onClick={()=>setMenuOpen(false)}><Icon name="close"/></button><a className="brand" href="#top"><span className="brand-mark">H</span><span><b>HOUSEOF</b><em>PASHM</em></span></a><nav><button onClick={()=>{setActiveCategory("All");setMenuOpen(false)}}>New arrivals</button>{categories.map(c=><button key={c.name} onClick={()=>{setActiveCategory(c.name);setMenuOpen(false);setTimeout(()=>goShop(c.name),50)}}>{c.name}</button>)}<a href="#story" onClick={()=>setMenuOpen(false)}>Our craft</a></nav></div>}
    {bagOpen&&<div className="overlay" onMouseDown={()=>setBagOpen(false)}><aside className="bag-drawer" onMouseDown={e=>e.stopPropagation()} aria-label="Shopping bag"><div className="bag-title"><div><span>YOUR BAG</span><h2>{cart.itemCount} {cart.itemCount===1?"item":"items"}</h2></div><button onClick={()=>setBagOpen(false)} aria-label="Close bag"><Icon name="close"/></button></div>{cart.items.length?<><div className="bag-list">{cart.items.map(item=><div className="bag-item" key={item.sku}><img src={item.image} alt=""/><div><b>{item.name}</b><span>{item.size?`Size: ${item.size}`:`SKU: ${item.sku}`}</span><label>Quantity <input type="number" min="1" max="10" value={item.quantity} onChange={event=>cart.setQuantity(item.sku,Number(event.target.value))}/></label><strong>₹{(item.unitPrice*item.quantity).toLocaleString("en-IN")}</strong></div><button onClick={()=>cart.removeItem(item.sku)}>Remove</button></div>)}</div><div className="bag-summary"><div><span>Estimated subtotal</span><b>₹{cart.displaySubtotal.toLocaleString("en-IN")}</b></div><Link className="checkout-link" href="/checkout">SECURE CHECKOUT</Link><small>Final prices and delivery are calculated securely on the server.</small></div></>:<div className="bag-empty"><Icon name="bag" size={34}/><h3>Your bag is waiting</h3><p>Add a piece you love and it will appear here.</p><button onClick={()=>{setBagOpen(false);goShop()}}>START SHOPPING</button></div>}</aside></div>}
    {supportWhatsapp&&<a className="whatsapp-float" href={`https://wa.me/${supportWhatsapp}?text=${encodeURIComponent("Hello HOUSEOFPASHM, I need help with a product or order.")}`} target="_blank" rel="noreferrer" aria-label="Get help on WhatsApp">WHATSAPP HELP</a>}
  </main>;
}
