"use client";

import { useMemo, useState } from "react";
import type { StorefrontCatalog, StorefrontProduct as Product } from "../lib/catalog/types";

function Icon({ name, size=20 }:{ name:"search"|"user"|"heart"|"bag"|"menu"|"close"|"arrow"; size?:number }) {
  const paths = {
    search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    user:<><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-4.7 3.5-7 8-7s7.2 2.3 8 7"/></>,
    heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>,
    bag:<><path d="M5 8h14l-1 13H6L5 8Z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/></>,
    menu:<><path d="M4 7h16M4 12h16M4 17h16"/></>, close:<><path d="m6 6 12 12M18 6 6 18"/></>, arrow:<><path d="M5 12h14M14 7l5 5-5 5"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function ProductCard({ product, saved, onSave, onAdd }:{ product:Product; saved:boolean; onSave:()=>void; onAdd:()=>void }) {
  const discount = Math.round((1-product.price/product.mrp)*100);
  return <article className="product-card">
    <div className="product-image-wrap"><img className="product-image" src={product.image} alt={product.name}/>{product.badge&&<span className="product-badge">{product.badge}</span>}<button className={`save-button ${saved?"saved":""}`} onClick={onSave} aria-label={saved?`Remove ${product.name} from wishlist`:`Save ${product.name} to wishlist`}><Icon name="heart" size={18}/></button><button className="quick-add" onClick={onAdd} disabled={!product.available}>{product.available?"ADD TO BAG":"OUT OF STOCK"}</button></div>
    <div className="product-info">{product.rating!==undefined&&product.reviews!==undefined&&<div className="rating"><strong>{product.rating}</strong><span>★</span><i></i><small>{product.reviews}</small></div>}<h3>{product.name}</h3><p>{product.subtitle}</p><div className="price-row"><strong>₹{product.price.toLocaleString("en-IN")}</strong><del>₹{product.mrp.toLocaleString("en-IN")}</del><span>({discount}% OFF)</span></div></div>
  </article>;
}

export default function Storefront({ products, categories, source }: StorefrontCatalog) {
  const [query,setQuery]=useState(""); const [activeCategory,setActiveCategory]=useState("All"); const [sort,setSort]=useState("recommended");
  const [wishlist,setWishlist]=useState<string[]>([]); const [wishOnly,setWishOnly]=useState(false); const [bag,setBag]=useState<Product[]>([]); const [bagOpen,setBagOpen]=useState(false); const [menuOpen,setMenuOpen]=useState(false);
  const filtered=useMemo(()=>{ const q=query.trim().toLowerCase(); let rows=products.filter(p=>(!wishOnly||wishlist.includes(p.id))&&(activeCategory==="All"||p.category===activeCategory)&&(!q||`${p.name} ${p.category} ${p.subtitle}`.toLowerCase().includes(q))); if(sort==="low")rows=[...rows].sort((a,b)=>a.price-b.price); if(sort==="high")rows=[...rows].sort((a,b)=>b.price-a.price); if(sort==="rating")rows=[...rows].sort((a,b)=>(b.rating??0)-(a.rating??0)); return rows; },[products,query,activeCategory,sort,wishOnly,wishlist]);
  const addToBag=(product:Product)=>{setBag(current=>[...current,product]);setBagOpen(true)}; const bagTotal=bag.reduce((sum,item)=>sum+item.price,0);
  const goShop=(category?:string)=>{setWishOnly(false);if(category)setActiveCategory(category);document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})};
  return <main data-catalog-source={source}>
    <div className="announcement">PAN-INDIA DELIVERY <span>•</span> FREE SHIPPING ABOVE ₹1,999 <span>•</span> EASY EXCHANGE</div>
    <header className="site-header"><button className="mobile-menu" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Icon name="menu"/></button><a className="brand" href="#top" aria-label="HOUSEOFPASHM home"><span className="brand-mark">H</span><span><b>HOUSEOF</b><em>PASHM</em></span></a><nav className="desktop-nav" aria-label="Main navigation">{categories.slice(0,5).map(c=><button key={c.name} onClick={()=>goShop(c.name)}>{c.name.toUpperCase()}</button>)}<button onClick={()=>document.getElementById("story")?.scrollIntoView({behavior:"smooth"})}>OUR CRAFT</button></nav><label className="search-box"><Icon name="search" size={19}/><input value={query} onChange={e=>{setQuery(e.target.value);setWishOnly(false)}} placeholder="Search for kurtis, stoles and more" aria-label="Search products"/></label><div className="header-actions"><button aria-label="Profile"><Icon name="user"/><span>Profile</span></button><button aria-label="Wishlist" onClick={()=>{setWishOnly(true);setActiveCategory("All");document.getElementById("shop")?.scrollIntoView({behavior:"smooth"})}}><Icon name="heart"/><span>Wishlist</span>{wishlist.length>0&&<b>{wishlist.length}</b>}</button><button aria-label="Shopping bag" onClick={()=>setBagOpen(true)}><Icon name="bag"/><span>Bag</span>{bag.length>0&&<b>{bag.length}</b>}</button></div></header>
    <section id="top" className="hero"><div className="hero-copy"><span className="eyebrow">THE KASHMIR EDIT • 2026</span><h1>Crafted in the valley.<br/><em>Styled for everywhere.</em></h1><p>Discover handpicked Aari embroidery, graceful silhouettes and everyday pieces that carry the soul of Kashmir.</p><div className="hero-buttons"><button onClick={()=>goShop()}>SHOP THE COLLECTION <Icon name="arrow" size={18}/></button><button className="ghost" onClick={()=>document.getElementById("story")?.scrollIntoView({behavior:"smooth"})}>OUR STORY</button></div><div className="hero-proof"><span><b>4.8 ★</b> loved by customers</span><span><b>100%</b> artisan-inspired</span></div></div><div className="hero-visual"><img src="https://houseofkari.in/cdn/shop/files/IMG_5287.heic?v=1739602272&width=2002" alt="Woman wearing a navy Kashmiri embroidered kurta"/><div className="hero-offer"><small>FESTIVE EDIT</small><strong>UP TO<br/>40% OFF</strong><span>Limited period</span></div><div className="hero-caption"><i></i><span>Hand-finished details<br/><b>Made to be noticed</b></span></div></div></section>
    <section className="category-section"><div className="section-heading"><span>SHOP BY CATEGORY</span><h2>Find your kind of elegance</h2></div><div className="category-row">{categories.map(c=><button key={c.name} className={activeCategory===c.name?"active":""} onClick={()=>goShop(c.name)}><span><img src={c.image} alt=""/></span><b>{c.name}</b><small>EXPLORE →</small></button>)}</div></section>
    <section className="benefit-strip"><div><span>✦</span><p><b>Curated craftsmanship</b><small>Details inspired by Kashmir</small></p></div><div><span>↺</span><p><b>Easy exchange</b><small>Shop with confidence</small></p></div><div><span>⌁</span><p><b>Pune to PAN India</b><small>Delivered to your doorstep</small></p></div><div><span>♡</span><p><b>Personal assistance</b><small>Style help on WhatsApp</small></p></div></section>
    <section id="shop" className="shop-section"><div className="shop-head"><div><span>CURATED FOR YOU</span><h2>{wishOnly?"Your wishlist":activeCategory==="All"?"Trending now":activeCategory}</h2><p>{filtered.length} styles</p></div><div className="filter-controls"><div className="chips"><button className={activeCategory==="All"&&!wishOnly?"active":""} onClick={()=>{setActiveCategory("All");setWishOnly(false)}}>All</button>{categories.map(c=><button key={c.name} className={activeCategory===c.name&&!wishOnly?"active":""} onClick={()=>{setActiveCategory(c.name);setWishOnly(false)}}>{c.name}</button>)}</div><label>Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="rating">Customer rating</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option></select></label></div></div>{filtered.length?<div className="product-grid">{filtered.map(product=><ProductCard key={product.id} product={product} saved={wishlist.includes(product.id)} onSave={()=>setWishlist(current=>current.includes(product.id)?current.filter(id=>id!==product.id):[...current,product.id])} onAdd={()=>addToBag(product)}/>)}</div>:<div className="empty-state"><h3>{wishOnly?"Your wishlist is empty":"No styles found"}</h3><p>{wishOnly?"Save your favourite pieces and find them here.":"Try a different search or browse all categories."}</p><button onClick={()=>{setQuery("");setActiveCategory("All");setWishOnly(false)}}>VIEW ALL STYLES</button></div>}</section>
    <section id="story" className="story-section"><div className="story-image"><img src="https://cdn.exoticindia.com/images/products/original/textiles-01-2025/gak603-lemonade_a04.webp" alt="Colourful Aari embroidered Kashmiri bag"/><span>THREAD BY THREAD</span></div><div className="story-copy"><span>BEAUTY WITH A BEGINNING</span><h2>Not just worn.<br/><em>Carried forward.</em></h2><p>HOUSEOFPASHM brings the valley’s visual poetry into the modern wardrobe—through joyful colour, delicate needlework and silhouettes made for real life.</p><div className="story-stats"><div><strong>01</strong><span>Curated pieces<br/>with character</span></div><div><strong>02</strong><span>Heritage details,<br/>modern styling</span></div><div><strong>03</strong><span>Personal service,<br/>wherever you are</span></div></div><a href="https://github.com/Ankush231994/houseofpashm" target="_blank" rel="noreferrer">VIEW THE PROJECT <Icon name="arrow" size={18}/></a></div></section>
    <section className="newsletter"><span>THE ELEGANCE LIST</span><h2>New drops. Styling notes. First access.</h2><p>Join the inner circle and get ₹200 off your first order above ₹1,999.</p><form onSubmit={e=>e.preventDefault()}><input type="email" required placeholder="Enter your email address" aria-label="Email address"/><button>JOIN NOW</button></form><small>By subscribing, you agree to receive brand updates. Unsubscribe anytime.</small></section>
    <footer><div className="footer-brand"><a className="brand" href="#top"><span className="brand-mark">H</span><span><b>HOUSEOF</b><em>PASHM</em></span></a><p>Bringing beauty from Kashmir to your wardrobe.</p><a href="https://github.com/Ankush231994/houseofpashm" target="_blank" rel="noreferrer">github.com/Ankush231994/houseofpashm</a></div><div><b>SHOP</b><a href="#shop">Kurtis</a><a href="#shop">Suit Sets</a><a href="#shop">Co-ord Sets</a><a href="#shop">Stoles & Bags</a></div><div><b>HELP</b><a href="#">Contact us</a><a href="#">Shipping</a><a href="#">Exchange policy</a><a href="#">Track order</a></div><div><b>LOCATION</b><p>Pune, Maharashtra<br/>Delivering PAN India</p><b className="mt">PAY SECURELY</b><p>UPI • Cards • COD</p></div><div className="copyright">© 2026 HOUSEOFPASHM. All rights reserved.<span>Crafted with care for a modern Kashmir.</span></div></footer>
    {menuOpen&&<div className="mobile-drawer"><button className="drawer-close" onClick={()=>setMenuOpen(false)}><Icon name="close"/></button><a className="brand" href="#top"><span className="brand-mark">H</span><span><b>HOUSEOF</b><em>PASHM</em></span></a><nav><button onClick={()=>{setActiveCategory("All");setMenuOpen(false)}}>New arrivals</button>{categories.map(c=><button key={c.name} onClick={()=>{setActiveCategory(c.name);setMenuOpen(false);setTimeout(()=>goShop(c.name),50)}}>{c.name}</button>)}<a href="#story" onClick={()=>setMenuOpen(false)}>Our craft</a></nav></div>}
    {bagOpen&&<div className="overlay" onMouseDown={()=>setBagOpen(false)}><aside className="bag-drawer" onMouseDown={e=>e.stopPropagation()}><div className="bag-title"><div><span>YOUR BAG</span><h2>{bag.length} {bag.length===1?"item":"items"}</h2></div><button onClick={()=>setBagOpen(false)}><Icon name="close"/></button></div>{bag.length?<><div className="bag-list">{bag.map((item,index)=><div className="bag-item" key={`${item.id}-${index}`}><img src={item.image} alt=""/><div><b>{item.name}</b><span>{item.size?`Size: ${item.size}`:`SKU: ${item.sku}`}</span><strong>₹{item.price.toLocaleString("en-IN")}</strong></div><button onClick={()=>setBag(current=>current.filter((_,i)=>i!==index))}>Remove</button></div>)}</div><div className="bag-summary"><div><span>Bag total</span><b>₹{bagTotal.toLocaleString("en-IN")}</b></div><div><span>Delivery</span><b className="free">FREE</b></div><button onClick={()=>alert("Checkout will connect to your payment and inventory system in the production version.")}>PLACE ORDER • ₹{bagTotal.toLocaleString("en-IN")}</button><small>Secure checkout • Easy exchange</small></div></>:<div className="bag-empty"><Icon name="bag" size={34}/><h3>Your bag is waiting</h3><p>Add a piece you love and it will appear here.</p><button onClick={()=>{setBagOpen(false);goShop()}}>START SHOPPING</button></div>}</aside></div>}
  </main>;
}
