import { notFound } from "next/navigation";
import Link from "next/link";

const policies = {
  privacy: { title: "Privacy policy", sections: [["Information we collect", "We collect the contact, delivery and order information needed to process purchases, provide support, prevent fraud and meet legal obligations. Payment card or UPI credentials are handled by the payment gateway and are not stored by HOUSEOFPASHM."], ["How information is used", "Order information is used for fulfilment, payment reconciliation, service messages, returns, security and required accounting. Marketing messages require a separate choice and can be stopped."], ["Sharing and retention", "Information may be shared with payment, hosting, email and delivery providers only as needed to operate the order. Retention periods and the final data-contact process must be approved before launch."], ["Your choices", "Customers may request access, correction or deletion where applicable by contacting the published support email. Some records may need to be retained for legal or accounting reasons."]] },
  terms: { title: "Terms of sale", sections: [["Products and availability", "Orders are accepted subject to stock, verified pricing, serviceability and payment confirmation. Handmade and craft-led products may have minor variations that should be described on each product page."], ["Payment and order acceptance", "Submitting payment does not by itself guarantee acceptance. An order becomes confirmed when HOUSEOFPASHM records successful payment and sends confirmation."], ["Customer responsibilities", "Customers must provide accurate delivery and contact information. Additional charges or delay caused by incorrect information may require customer confirmation."], ["Governing details", "The final seller identity, jurisdiction, grievance contact and dispute terms must be reviewed and inserted before this draft can be published for live sales."]] },
  shipping: { title: "Shipping policy", sections: [["Coverage", "The intended launch region is India. Serviceability, dispatch days, delivery estimates and charges depend on the courier decision and must be confirmed before accepting live orders."], ["Tracking", "When an order is shipped, the operator records the courier and tracking number. Customers can use the Track Order page or the courier link supplied in the shipping message."], ["Delays and failed delivery", "Weather, remote-area service and courier exceptions can cause delay. The final procedure for failed delivery, return-to-origin and address correction must match the selected courier contract."]] },
  returns: { title: "Returns and exchanges", sections: [["Eligibility", "This is a launch draft. The final return/exchange window, product-condition requirements, exclusions for customised or hygiene-sensitive goods and who pays return shipping must be approved by the owner before live sales."], ["Request process", "Customers should contact support with the order number, reason and clear product photos. The operator records the decision and instructions; customers should not send goods without approval."], ["Refund timing", "Approved refunds are initiated through the original payment method. Bank and gateway processing times vary and must be stated using the confirmed Razorpay operating policy."]] },
  cancellation: { title: "Cancellation and refund policy", sections: [["Before dispatch", "The final cancellation cutoff must be approved. Operators must not promise cancellation after packing or dispatch unless the actual fulfilment process supports it."], ["After payment", "A payment refund must be requested and reconciled through the payment gateway. An internal status change alone is not proof that money was returned."], ["Damaged or incorrect items", "Customers should report the issue promptly with the order number and photographs. The approved resolution may be replacement, exchange or refund according to the final returns policy."]] },
} as const;

export default async function PolicyPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const policy = policies[slug as keyof typeof policies]; if (!policy) notFound();
  const configured = Boolean(process.env.SELLER_LEGAL_NAME && process.env.SELLER_POSTAL_ADDRESS && process.env.SUPPORT_EMAIL);
  return <main className="policy-page"><header className="simple-header"><Link className="brand" href="/"><span className="brand-mark">H</span><span><b>HOUSEOF</b><em>PASHM</em></span></Link><Link href="/">BACK TO SHOP</Link></header><article><span className="eyebrow">CUSTOMER INFORMATION</span><h1>{policy.title}</h1>{!configured&&<div className="policy-draft" role="note"><b>DRAFT — NOT APPROVED FOR LIVE SALES</b><p>Seller identity, address, support contact and operating rules are incomplete. Follow the owner setup guide before publishing.</p></div>}{policy.sections.map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}<section><h2>Contact</h2><p>{process.env.SELLER_LEGAL_NAME??"[LEGAL SELLER NAME REQUIRED]"}<br/>{process.env.SELLER_POSTAL_ADDRESS??"[POSTAL ADDRESS REQUIRED]"}<br/>{process.env.SUPPORT_EMAIL??"[SUPPORT EMAIL REQUIRED]"}</p></section><small>Draft last updated 15 August 2026. Obtain qualified legal and tax review before launch.</small></article></main>;
}
